/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.com.s3playground

import aws.sdk.kotlin.services.s3.S3Client
import aws.sdk.kotlin.services.s3.model.PutObjectRequest
import aws.sdk.kotlin.services.s3.model.StorageClass
import aws.sdk.kotlin.services.s3.putObject
import aws.sdk.kotlin.runtime.auth.credentials.ProfileCredentialsProvider
import aws.smithy.kotlin.runtime.content.ByteStream
import java.io.File
import kotlinx.coroutines.runBlocking

class App {
    fun uploadFile(): Unit = runBlocking {
        val filePath = System.getProperty("user.dir")+"/file_test"

        val file = File(filePath)
        S3Client
        // S3Client
        //     .fromEnvironment { region = "sa-east-1" }
        //     .use {
        //         it.putObject{ 
        //             bucket = "cadunico"
        //             key = file.name
        //             body = ByteStream.fromBytes(file.readBytes())
        //         }
        //     }

        val s3Client = S3Client{
            region = "sa-east-1"
            credentialsProvider = ProfileCredentialsProvider(profileName = "conta-pessoal")
        }

        s3Client.putObject { 
            bucket = "cadunico"
            key = file.name
            body = ByteStream.fromBytes(file.readBytes())
            storageClass = StorageClass.fromValue("ONEZONE_IA")
         }

        print("OK")
    }
}

fun main() {
    App().uploadFile()
}
